<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $clients = [
            [
                'company_name' => 'TechVolt Industries (Pvt) Ltd',
                'client_code' => 'CLT-001',
                'client_type' => 'corporate',
                'address' => 'Plot 45, Industrial Estate',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '75700',
                'phone' => '+92-21-3456789',
                'email' => 'info@techvolt.com',
                'website' => 'https://techvolt.com',
                'contact_person' => 'Ahmed Hassan',
                'contact_phone' => '+92-300-1234567',
                'contact_email' => 'ahmed.hassan@techvolt.com',
                'tax_id' => 'TAX-12345678',
                'business_registration_number' => 'BRN-987654321',
                'payment_terms' => 'net_30',
                'credit_limit' => 500000.00,
                'current_balance' => 0.00,
                'credit_status' => 'good',
                'notes' => 'Major client for electrical appliance testing',
                'is_active' => true,
            ],
            [
                'company_name' => 'PowerGrid Solutions',
                'client_code' => 'CLT-002',
                'client_type' => 'corporate',
                'address' => '789 Business Bay, Tower C',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '54000',
                'phone' => '+92-42-6789012',
                'email' => 'contact@powergrid.pk',
                'website' => 'https://powergrid.pk',
                'contact_person' => 'Fatima Khan',
                'contact_phone' => '+92-321-9876543',
                'contact_email' => 'fatima.khan@powergrid.pk',
                'tax_id' => 'TAX-87654321',
                'business_registration_number' => 'BRN-123456789',
                'payment_terms' => 'net_45',
                'credit_limit' => 750000.00,
                'current_balance' => 0.00,
                'credit_status' => 'good',
                'notes' => 'Power distribution equipment manufacturer',
                'is_active' => true,
            ],
            [
                'company_name' => 'Ministry of Energy - Testing Division',
                'client_code' => 'CLT-003',
                'client_type' => 'government',
                'address' => 'Government Complex, Sector G-5',
                'city' => 'Islamabad',
                'state' => 'Federal Capital',
                'country' => 'Pakistan',
                'postal_code' => '44000',
                'phone' => '+92-51-9201234',
                'email' => 'testing@energy.gov.pk',
                'website' => 'https://energy.gov.pk',
                'contact_person' => 'Dr. Imran Ali',
                'contact_phone' => '+92-51-9204567',
                'contact_email' => 'imran.ali@energy.gov.pk',
                'tax_id' => null,
                'business_registration_number' => 'GOV-2023-001',
                'payment_terms' => 'net_60',
                'credit_limit' => 1000000.00,
                'current_balance' => 0.00,
                'credit_status' => 'good',
                'notes' => 'Government agency - requires special documentation',
                'is_active' => true,
            ],
            [
                'company_name' => 'ElectroMax Manufacturing',
                'client_code' => 'CLT-004',
                'client_type' => 'sme',
                'address' => '123 Small Industries Zone',
                'city' => 'Sialkot',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '51310',
                'phone' => '+92-52-4567890',
                'email' => 'info@electromax.com',
                'website' => 'https://electromax.com',
                'contact_person' => 'Bilal Mahmood',
                'contact_phone' => '+92-345-6789012',
                'contact_email' => 'bilal@electromax.com',
                'tax_id' => 'TAX-45678901',
                'business_registration_number' => 'BRN-567890123',
                'payment_terms' => 'net_15',
                'credit_limit' => 150000.00,
                'current_balance' => 0.00,
                'credit_status' => 'good',
                'notes' => 'Small to medium enterprise - electrical components',
                'is_active' => true,
            ],
            [
                'company_name' => 'Smart Home Technologies',
                'client_code' => 'CLT-005',
                'client_type' => 'corporate',
                'address' => '567 Tech Hub, Innovation Center',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '75600',
                'phone' => '+92-21-8901234',
                'email' => 'testing@smarthome.pk',
                'website' => 'https://smarthome.pk',
                'contact_person' => 'Sarah Ahmed',
                'contact_phone' => '+92-333-2345678',
                'contact_email' => 'sarah.ahmed@smarthome.pk',
                'tax_id' => 'TAX-23456789',
                'business_registration_number' => 'BRN-345678901',
                'payment_terms' => 'net_30',
                'credit_limit' => 300000.00,
                'current_balance' => 0.00,
                'credit_status' => 'good',
                'notes' => 'IoT and smart electrical devices manufacturer',
                'is_active' => true,
            ],
            [
                'company_name' => 'National Appliances Corporation',
                'client_code' => 'CLT-006',
                'client_type' => 'corporate',
                'address' => '890 Corporate Avenue',
                'city' => 'Faisalabad',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '38000',
                'phone' => '+92-41-1112222',
                'email' => 'quality@natappliances.com',
                'website' => 'https://natappliances.com',
                'contact_person' => 'Usman Tariq',
                'contact_phone' => '+92-300-9998888',
                'contact_email' => 'usman.tariq@natappliances.com',
                'tax_id' => 'TAX-34567890',
                'business_registration_number' => 'BRN-456789012',
                'payment_terms' => 'net_30',
                'credit_limit' => 600000.00,
                'current_balance' => 0.00,
                'credit_status' => 'good',
                'notes' => 'Major home appliances manufacturer',
                'is_active' => true,
            ],
        ];

        foreach ($clients as $client) {
            Client::create($client);
        }
    }
}
