<?php

namespace Database\Seeders;

use App\Models\Manufacturer;
use Illuminate\Database\Seeder;

class ManufacturerSeeder extends Seeder
{
    public function run(): void
    {
        $manufacturers = [
            [
                'company_name' => 'Siemens Pakistan Engineering Co. Ltd',
                'brand_name' => 'Siemens',
                'manufacturer_code' => 'MFR-001',
                'address' => '123 Industrial Avenue',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '75100',
                'phone' => '+92-21-111-743-636',
                'email' => 'info.pk@siemens.com',
                'website' => 'https://siemens.com.pk',
                'contact_person' => 'Ali Raza',
                'contact_phone' => '+92-300-1111111',
                'contact_email' => 'ali.raza@siemens.com',
                'tax_id' => 'TAX-SIE-001',
                'certifications' => 'ISO 9001, ISO 14001, CE, UL',
                'is_active' => true,
            ],
            [
                'company_name' => 'ABB Pakistan',
                'brand_name' => 'ABB',
                'manufacturer_code' => 'MFR-002',
                'address' => '456 Technology Park',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '54000',
                'phone' => '+92-42-111-222-111',
                'email' => 'contact@pk.abb.com',
                'website' => 'https://abb.com.pk',
                'contact_person' => 'Hassan Malik',
                'contact_phone' => '+92-321-2222222',
                'contact_email' => 'hassan.malik@abb.com',
                'tax_id' => 'TAX-ABB-002',
                'certifications' => 'ISO 9001, IEC 61439, CE',
                'is_active' => true,
            ],
            [
                'company_name' => 'Schneider Electric Pakistan',
                'brand_name' => 'Schneider Electric',
                'manufacturer_code' => 'MFR-003',
                'address' => '789 Business District',
                'city' => 'Islamabad',
                'state' => 'Federal Capital',
                'country' => 'Pakistan',
                'postal_code' => '44000',
                'phone' => '+92-51-111-763-363',
                'email' => 'pakistan@schneider-electric.com',
                'website' => 'https://schneider-electric.com.pk',
                'contact_person' => 'Ayesha Khan',
                'contact_phone' => '+92-333-3333333',
                'contact_email' => 'ayesha.khan@se.com',
                'tax_id' => 'TAX-SCH-003',
                'certifications' => 'ISO 9001, ISO 45001, RoHS',
                'is_active' => true,
            ],
            [
                'company_name' => 'Philips Lighting Pakistan',
                'brand_name' => 'Philips',
                'manufacturer_code' => 'MFR-004',
                'address' => '321 Commerce Street',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '75300',
                'phone' => '+92-21-111-445-477',
                'email' => 'info.pk@philips.com',
                'website' => 'https://philips.com.pk',
                'contact_person' => 'Zainab Ahmed',
                'contact_phone' => '+92-300-4444444',
                'contact_email' => 'zainab.ahmed@philips.com',
                'tax_id' => 'TAX-PHI-004',
                'certifications' => 'ISO 9001, Energy Star, CE',
                'is_active' => true,
            ],
            [
                'company_name' => 'Haier Pakistan',
                'brand_name' => 'Haier',
                'manufacturer_code' => 'MFR-005',
                'address' => '555 Industrial Zone',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '54700',
                'phone' => '+92-42-111-111-456',
                'email' => 'info@haier.com.pk',
                'website' => 'https://haier.com.pk',
                'contact_person' => 'Bilal Hassan',
                'contact_phone' => '+92-321-5555555',
                'contact_email' => 'bilal.hassan@haier.com',
                'tax_id' => 'TAX-HAI-005',
                'certifications' => 'ISO 9001, SASO, CE',
                'is_active' => true,
            ],
            [
                'company_name' => 'Dawlance Electronics',
                'brand_name' => 'Dawlance',
                'manufacturer_code' => 'MFR-006',
                'address' => '888 Manufacturing Hub',
                'city' => 'Karachi',
                'state' => 'Sindh',
                'country' => 'Pakistan',
                'postal_code' => '75850',
                'phone' => '+92-21-111-329-526',
                'email' => 'info@dawlance.com.pk',
                'website' => 'https://dawlance.com.pk',
                'contact_person' => 'Faisal Mahmood',
                'contact_phone' => '+92-300-6666666',
                'contact_email' => 'faisal.mahmood@dawlance.com',
                'tax_id' => 'TAX-DAW-006',
                'certifications' => 'ISO 9001, PSQCA, CE',
                'is_active' => true,
            ],
            [
                'company_name' => 'Orient Electronics',
                'brand_name' => 'Orient',
                'manufacturer_code' => 'MFR-007',
                'address' => '999 Electric Avenue',
                'city' => 'Lahore',
                'state' => 'Punjab',
                'country' => 'Pakistan',
                'postal_code' => '54600',
                'phone' => '+92-42-111-674-368',
                'email' => 'info@orientelectronics.com',
                'website' => 'https://orientelectronics.com',
                'contact_person' => 'Sana Iqbal',
                'contact_phone' => '+92-321-7777777',
                'contact_email' => 'sana.iqbal@orient.com',
                'tax_id' => 'TAX-ORI-007',
                'certifications' => 'ISO 9001, PSQCA',
                'is_active' => true,
            ],
        ];

        foreach ($manufacturers as $manufacturer) {
            Manufacturer::create($manufacturer);
        }
    }
}

